### ISSUE TITLE
A few small quetions about the WP

### ISSUE THREAD

**Issue by serejandmyself** [kleros/kleros-papers#11]
Hey!

Enjoyed reading your documentation. Seems like a very interesting project, although I do have some questions left:

- How are you planning to scale to other protocols? 
Lets say BTC (would something like the NiPoWPoW contracts make it possible to use in other PoW chains?)
- Can Aragon offer a similar solution to what you are offering? Especially in terms of Aragon already being in place (not saying it is better)
- Can you expand on the "token distribution event" details? 
As in: this is a vital fail/success point for this kind of project in my opinion (or any other project to be precise). A bad distribution would totally fail the project. Anything like an ICO would also fail it (concentrated juror token in the hands of those who have more money). 
What might work, is maybe using some kind of a distributed random system, alongside some kind of a claiming system, that can get a fairer distribution of the tokens.
- There is a slight mention of a reputation system (one place I believe), but in theory, wouldn't you need a very strong and a very powerful reputation system that can objectively (rather than subjectively), decide (based on an algorithm, not human mistake) a simple reputation score (lets say 0-5). IMO, that would help to decide quite a number of things.

In any case. Seems like an interesting project. Do not take those questions, as something else, but subjective opinion and interest in your project, please.

BR

**Comment by epiqueras** [comment]
Hi Serej, thanks, we think so too :). I'll do my best to answer your questions.

- Yeah we can have Kleros court contracts on other chains and move PNK across through bridges or atomic swaps. If a Kleros court can trigger enforcement on another chain remotely at a reasonable price, then even better.

- Aragon is more geared towards general governance. Kleros is optimized for dispute resolution and compositions of it, e.g. Oracles, Curated/Ranked Lists. So we are similar, but not the same.

- Yes absolutely. We plan on encouraging early jurors with PNK airdrops and setting up systems that will prime the subcourts with high quality populations of jurors. The platform that supplies disputes first will heavily influence who our first jurors are. (Most Ebay community moderators are Ebay users themselves.) So, yeah, claimable airdrops are a good idea.

- Reputation can be derived from coherent/incoherent vote history. But, adding reputation to Kleros would be tricky as it would decrease the effect of PNK redistribution. We are still open to researching this topic more further down the line as having some sort of signal of coherence that cannot be bought might be useful and not harmful in some places like subcourt governance. A community member recently wrote about this here: https://docs.google.com/document/d/1bQAQ0tN7rt0TQBhz9ftbscJXNEeXMw-y66BDUswi3Yg/edit

Thanks for taking interest in the project. You can find most of us on Slack to chat about any of these things at any time. You are also welcome to any of our open weekly calls. I think you would enjoy Wednesday's research call at 14:00 UTC.

https://slack.kleros.io

**Comment by serejandmyself** [comment]
Thanks for the answers, Enrique!

- Is there any information available about the technology used behind the bridges?

- I had a look at the document and I guess its more of a study (which is great of course). I was implying more towards, whether or not, you have a rough idea of what system you want to implement.
It is obvious it has to be based on an open source tech and include not only algos but also have some kind of fundamental reasoning behind it.

Thank you for the slack invitation. I will try to check out the open call and also will try to see if I can send you any interesting reputation models that are available on the market already.

**Comment by epiqueras** [comment]
I think Cosmos' IBC is one of the leading specs:
https://cosmos.network/docs/spec/ibc/

We don't have plans for implementing reputation in the near future.

Looking forward to reading them :)
